/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './app/**/*.{js,ts,jsx,tsx}',
    './components/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        // Material Design 3 colors
        primary: '#6750a4',
        'primary-container': '#eaddff',
        secondary: '#625b71',
        'secondary-container': '#e8def8',
        tertiary: '#7d5260',
        'tertiary-container': '#ffd8e4',
        error: '#b3261e',
        'error-container': '#f9dedc',
        outline: '#79747e',
        'outline-variant': '#cac7d0',
        background: '#fffbfe',
        surface: '#fffbfe',
        'surface-variant': '#eae7f0',
        'surface-container': '#f3eff5',
        'surface-container-high': '#ece6f0',
        'surface-container-highest': '#e6dce6',
        'surface-container-lowest': '#fef7ff',
        'surface-container-low': '#f9f5fa',
        'on-primary': '#ffffff',
        'on-primary-container': '#21005d',
        'on-primary-fixed': '#ffffff',
        'on-primary-fixed-dim': '#eaddff',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#1d192b',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#31111d',
        'on-error': '#ffffff',
        'on-error-container': '#410e0b',
        'on-surface': '#1c1b1f',
        'on-surface-variant': '#49454e',
        'on-background': '#1c1b1f',
        'secondary-fixed': '#f3eff5',
        'secondary-fixed-dim': '#dbd7e8',
        'tertiary-fixed': '#ffd8e4',
        'tertiary-fixed-dim': '#e4b8c8',
        'inverse-surface': '#313033',
        'inverse-on-surface': '#f4eff4',
        'inverse-primary': '#d0bcff',
      },
      fontFamily: {
        headline: 'var(--font-headline, system-ui)',
        body: 'var(--font-body, system-ui)',
        math: 'var(--font-math, system-ui)',
      },
      fontSize: {
        xs: ['12px', { lineHeight: '16px' }],
        sm: ['14px', { lineHeight: '20px' }],
        base: ['16px', { lineHeight: '24px' }],
        lg: ['18px', { lineHeight: '28px' }],
        xl: ['20px', { lineHeight: '28px' }],
        '2xl': ['24px', { lineHeight: '32px' }],
        '3xl': ['28px', { lineHeight: '36px' }],
        '4xl': ['32px', { lineHeight: '40px' }],
        '5xl': ['40px', { lineHeight: '48px' }],
      },
    },
  },
  plugins: [],
}
